### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tommygebru** [sedevans/prj-rev-bwfs-dasmoto#9]
Hey Edward, really great effort on your first project, I think it was top-notch 🎉  You have a solid grasp of best practices and are well on your way to creating quality work.

Spend a little more time reviewing/practicing upon the feedback until it clicks, and I'm confident you'll do fine.

https://github.com/thenerdery/html-css-standards
This really is a great cheatsheet/project to reference, its a short and to the point material on css and html best practices

Ok Edward keep up the good work and happy coding!

**Comment by sedevans** [comment]
Thanks, Tommy!

A few things I'll be following up on after this...

- Read through the Nerdery html-css-standards 
- Pay closer attention to nested structure of HTML5 semantic tags
- Shoot for DRY CSS
- Install/learn how to use spell-check and a linter in Atom 

Cheers,
Ed E.
